checks:
  cpuRequestsMissing: warning
  memoryRequestsMissing: warning
  cpuLimitsMissing: warning
  memoryLimitsMissing: warning
  notReadOnlyRootFilesystem: warning
  privilegeEscalationAllowed: danger
  runAsRootAllowed: warning
  insecureCapabilities: danger
  hostNetworkSet: warning
  hostPIDSet: danger
  hostIPCSet: danger
  pullPolicyNotAlways: ignore
  tagNotSpecified: warning
  priorityClassNotSet: warning
  missingPodDisruptionBudget: warning

exemptions:
  - namespace: kube-system
    controllerNames:
      - kube-flannel
    rules:
      - hostNetworkSet
      - runAsRootAllowed
      - privilegeEscalationAllowed
      - insecureCapabilities

  - namespace: kube-system
    controllerNames:
      - coredns
    rules:
      - priorityClassNotSet

  - namespace: kube-system
    controllerNames:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler
    rules:
      - hostNetworkSet
      - notReadOnlyRootFilesystem

  - namespace: longhorn-system
    controllerNames:
      - longhorn-manager
      - longhorn-csi-plugin
    rules:
      - hostNetworkSet
      - runAsRootAllowed
      - privilegeEscalationAllowed
      - insecureCapabilities
