apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-coredns
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./03-infrastructure/clusters/talos-homelab/coredns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-metallb
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./03-infrastructure/infrastructure/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-metallb-config
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-metallb
  interval: 10m0s
  path: ./03-infrastructure/clusters/talos-homelab/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-traefik
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-metallb-config
  interval: 10m0s
  path: ./03-infrastructure/infrastructure/traefik/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cloudnative-pg
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-longhorn
  interval: 10m0s
  path: ./03-infrastructure/infrastructure/cloudnative-pg/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./03-infrastructure/infrastructure/cert-manager/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-metrics-server
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./03-infrastructure/infrastructure/metrics-server/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-longhorn
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./03-infrastructure/infrastructure/longhorn/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-longhorn-ingress
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-longhorn
  - name: infrastructure-traefik
  interval: 10m0s
  path: ./03-infrastructure/infrastructure/longhorn/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-observability
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-longhorn
  interval: 10m0s
  path: ./03-infrastructure/clusters/talos-homelab/.generated/observability
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-traefik-monitoring
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-traefik
  - name: infrastructure-observability
  interval: 10m0s
  path: ./03-infrastructure/infrastructure/traefik/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-longhorn-monitoring
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-longhorn
  - name: infrastructure-observability
  interval: 10m0s
  path: ./03-infrastructure/infrastructure/longhorn/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-alloy
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-observability
  interval: 10m0s
  path: ./03-infrastructure/clusters/talos-homelab/.generated/alloy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-flux-monitoring
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-observability
  interval: 10m0s
  path: ./03-infrastructure/clusters/talos-homelab/flux-monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager-monitoring
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-cert-manager
  - name: infrastructure-observability
  interval: 10m0s
  path: ./03-infrastructure/infrastructure/cert-manager/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cloudnative-pg-monitoring
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-cloudnative-pg
  - name: infrastructure-observability
  interval: 10m0s
  path: ./03-infrastructure/infrastructure/cloudnative-pg/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-alloy-monitoring
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-alloy
  - name: infrastructure-observability
  interval: 10m0s
  path: ./03-infrastructure/infrastructure/alloy/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
