apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alloy
  namespace: alloy
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - alloy
  selector:
    matchLabels:
      app.kubernetes.io/instance: alloy
      app.kubernetes.io/name: alloy
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics
