apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-cloudnative-pg
  namespace: cnpg-system
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - cnpg-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: cnpg
      app.kubernetes.io/name: cloudnative-pg
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: /metrics
