apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-credentials
    namespace: pgadmin
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:P5pMnzgAV1ECLt+HDnye5Wy28UPnH+v9xb/n4t6OzmA=,iv:qE4r4bYKt5pXdtF3rWObkZc2Pgy64ReKv5SgIje46RY=,tag:6lr+lbHhSiyJlY1uPT4ZMA==,type:str]
sops:
    age:
        - recipient: age1qx9cx5rthaaqt3a5cz39yn5rtc0fx9e2drxvr77cpkl04emnz4assc9y0m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ0dsVnBaZGZTUVJQNldG
            Q2VnWW5IbFdGSGxnblZ6MS9XOFQwVU5nNXd3CkFUMFVQbHJPR2YvU2pkM0NjNDZB
            KzFaQlVaOWF6Y2dKTnYyMXphcTdVcHcKLS0tIC8xYlNXc0NtdFp6Q1hMbGhTaERq
            TG5uemdXVldWNzk3VGl0MkpCMEtxOXcKDJTJCyRK65WqExdyDXFWfuEl36p8OauG
            rH9/BuFUR3QmgD7OX9xZ40qoCcyYyEcgPI/0l8QbsiZHKPBpatz9dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T14:26:03Z"
    mac: ENC[AES256_GCM,data:J8wI0noI+mbj857zRsq9uONwuYHPWoszJ7gjL6la6JyDfsoMw6v3+ZYAena5X2qzPd8jwz0y4dL0dj5lhAYRjCGr9DyoMtB+uWIcnNBsBHoKDnVMnMjbAyvxeuIBBnyDYBaC5CKsiGpMBiJ/Nbmi5lF2SEgBsdo4Hmt+dCHPn+c=,iv:9zYkffWQZxwmWHZdNSylF/XwiuF4V2vNo+Wwgx7k1Hw=,tag:EA8jEoOfBEa8ttjSmOyNEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
