- op: add
  path: /spec/values/env
  value:
    email: pgadmin@home.de
- op: replace
  path: /spec/values/persistentVolume/size
  value: 5Gi
- op: replace
  path: /spec/values/ingress/hosts
  value:
    - host: pgadmin.home.arpa
      paths:
        - path: /
          pathType: Prefix
