apiVersion: v1
kind: Secret
metadata:
    name: appdb-app-user
    namespace: postgres-smoke
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:he4U,iv:A0N628cJ2XcbTN6tdN850EO4qgOYXKLFi8AlfXjpzYQ=,tag:TxAkOHIhSSS0+WX5TkQXTw==,type:str]
    password: ENC[AES256_GCM,data:O2iFQuW7ZW3VAeXPX0XIiSxtFU/or2VLK9oepSF/bh2B,iv:cJfgU8QVHDzbhnAZdnxl9F1M7ch/bsPKWtLiBY0RGUc=,tag:VM3qh6vejyyLRBTgWzy5Vg==,type:str]
sops:
    age:
        - recipient: age1k9r7zw2pvhp0u0ua23zr66xe9jm5s5ywxe65qw4pp7wh6e8clycsxk3209
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWHE0MFQwSDJmM1VGNElj
            ZldGODl2U0hTMUlwd1o4ZTJVaWlQcmljY0FnCnVTQU9ncEF1YkY5NEtWYmNUTVhx
            MTdnZGdVdC8wSlVWbENyQWJKNVZudW8KLS0tIGVuQUc1RS9OUWF4RlhoNDFGOENv
            OG10MGNJbXRrUlZyUjhiQjFPcE9HTDgKcHkgWoTh5hxbDepM3d7JTEhRB1wQUX94
            P2PjbSXjzOyNfUhYzEE0aVyT0Zs15BAbdFXdDPpsfVnr1xXT1ap1PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T13:25:15Z"
    mac: ENC[AES256_GCM,data:TPlvgvHzBZvwF7bFlrrjSMfSmi80F2pyxnwfSYmtdbOWCLNbvSSec02RZO8rlTx53TsGQBJKzZ0L3qOHDx3ke6eMKIgeVF0GaJPf0MdBATmj3Xbj1wvHr0db7Hu/Jh9DP+EprBqauEofngSfQeyHI6HsuQ9jTCD7sv70BCh+BIs=,iv:JlaQFIhG4Vrq3S4GdHmYpcD6ZJtVDwR/JsLIXO3GouQ=,tag:V06LMZY825Q7Hh/Turin1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: appdb-superuser
    namespace: postgres-smoke
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:HEyIt89Sw+Q=,iv:/3Vbw/5nt4ZStHosk4xXvuqEM5UYqJVigbBY45lr9Q8=,tag:TpufD2h5VsTII/NgQ7OFtQ==,type:str]
    password: ENC[AES256_GCM,data:orYy2GEHo/JqKiighphYceOtwcP6m/7F2D2o,iv:vKcSaaaY68NFptEuYpnQQ3TuQGSkl+7KfLJ2BLUoRhA=,tag:nW4+ggG+Y1W0WzpKoHST1w==,type:str]
sops:
    age:
        - recipient: age1k9r7zw2pvhp0u0ua23zr66xe9jm5s5ywxe65qw4pp7wh6e8clycsxk3209
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWHE0MFQwSDJmM1VGNElj
            ZldGODl2U0hTMUlwd1o4ZTJVaWlQcmljY0FnCnVTQU9ncEF1YkY5NEtWYmNUTVhx
            MTdnZGdVdC8wSlVWbENyQWJKNVZudW8KLS0tIGVuQUc1RS9OUWF4RlhoNDFGOENv
            OG10MGNJbXRrUlZyUjhiQjFPcE9HTDgKcHkgWoTh5hxbDepM3d7JTEhRB1wQUX94
            P2PjbSXjzOyNfUhYzEE0aVyT0Zs15BAbdFXdDPpsfVnr1xXT1ap1PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T13:25:15Z"
    mac: ENC[AES256_GCM,data:TPlvgvHzBZvwF7bFlrrjSMfSmi80F2pyxnwfSYmtdbOWCLNbvSSec02RZO8rlTx53TsGQBJKzZ0L3qOHDx3ke6eMKIgeVF0GaJPf0MdBATmj3Xbj1wvHr0db7Hu/Jh9DP+EprBqauEofngSfQeyHI6HsuQ9jTCD7sv70BCh+BIs=,iv:JlaQFIhG4Vrq3S4GdHmYpcD6ZJtVDwR/JsLIXO3GouQ=,tag:V06LMZY825Q7Hh/Turin1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
