apiVersion: v1
kind: Secret
metadata:
    name: appdb-app-user
    namespace: postgres-smoke
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:bCKY,iv:Jdwo7bCoZFocw08b4N3s10M817yZ1U7hxO2rZNSRHqo=,tag:MyU+C4ercmuLmPuKfPDXEQ==,type:str]
    password: ENC[AES256_GCM,data:pDtoUZiSLk9OmV0=,iv:1FS1/lwWTOyOP/0d3KP6wK8NdLoEZ+dhVT6Z/vTCsgU=,tag:ycDoPWoY8dSaBz2E9RLmUA==,type:str]
sops:
    age:
        - recipient: age1qx9cx5rthaaqt3a5cz39yn5rtc0fx9e2drxvr77cpkl04emnz4assc9y0m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU3d4WlRIWHpxbHdOU2FN
            d0tMWGZjdlVLYzZoVklCaFMyU0FyL2s0bjFZClVEY3M2RVdLdU92azBFMDF4Yndl
            Z1hGcEZLbWlEejIrRGtaME5hYmZ4OFUKLS0tIGcwU2xyTWRvS0RHbTRBS0t6QjM5
            cCtsYmp1bXk4UXRFNWJCa3J6Wk1QYzQKKcD3KYfAyDmjYTGwhf75O1wg95u0xuvB
            6cMl+S+v1HbGTu3ZxYLTL0wDBabljT4ivt9ufDS0SfjPMl+rxJtw3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T13:38:21Z"
    mac: ENC[AES256_GCM,data:P/ws8DY8g1kbbrFbZLyD1WcVa+ZGTlmCW5sc5CFt6gilpPo33tzpCoqzQj0CxpnsJJDvLT3xq6OplzNxekfoiH7AlBYl4s9qVfIiPnQPEaH+dp/W14VCsnLbHXEdVCwcYDpgxEBIcGmyLvb7AHbKXEtfZpF/UJ7PK8CIoR4fKK0=,iv:L99Exkh1TQX3MyA4OoBVqDowi+f/XMy5lCu/esu4E4s=,tag:GtPNUesZFl5moJjXwhzgdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: appdb-superuser
    namespace: postgres-smoke
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0d8qxvP8nLI=,iv:SyCJAmUQSnlJVHi20y0pvWxVhZYTxNI+Vw215K8MO98=,tag:C59Ykaur0el6qCXweYKrKg==,type:str]
    password: ENC[AES256_GCM,data:HQl35XhXxy82f1I=,iv:44dNXYTr/i5qlAKxrWfGjJntwxnoBui72fhoNCwVPzU=,tag:k/3Qc+E1U6bNtGrIeWQpHg==,type:str]
sops:
    age:
        - recipient: age1qx9cx5rthaaqt3a5cz39yn5rtc0fx9e2drxvr77cpkl04emnz4assc9y0m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU3d4WlRIWHpxbHdOU2FN
            d0tMWGZjdlVLYzZoVklCaFMyU0FyL2s0bjFZClVEY3M2RVdLdU92azBFMDF4Yndl
            Z1hGcEZLbWlEejIrRGtaME5hYmZ4OFUKLS0tIGcwU2xyTWRvS0RHbTRBS0t6QjM5
            cCtsYmp1bXk4UXRFNWJCa3J6Wk1QYzQKKcD3KYfAyDmjYTGwhf75O1wg95u0xuvB
            6cMl+S+v1HbGTu3ZxYLTL0wDBabljT4ivt9ufDS0SfjPMl+rxJtw3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T13:38:21Z"
    mac: ENC[AES256_GCM,data:P/ws8DY8g1kbbrFbZLyD1WcVa+ZGTlmCW5sc5CFt6gilpPo33tzpCoqzQj0CxpnsJJDvLT3xq6OplzNxekfoiH7AlBYl4s9qVfIiPnQPEaH+dp/W14VCsnLbHXEdVCwcYDpgxEBIcGmyLvb7AHbKXEtfZpF/UJ7PK8CIoR4fKK0=,iv:L99Exkh1TQX3MyA4OoBVqDowi+f/XMy5lCu/esu4E4s=,tag:GtPNUesZFl5moJjXwhzgdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
