apiVersion: v1
kind: Service
metadata:
  name: appdb-rw-lb
  namespace: postgres-smoke
  labels:
    app.kubernetes.io/name: appdb-rw-lb
    cnpg.io/cluster: appdb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: appdb
    cnpg.io/instanceRole: primary
