apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - cert-manager
  selector:
    matchExpressions:
    - key: app.kubernetes.io/instance
      operator: In
      values:
      - cert-manager
    - key: app.kubernetes.io/name
      operator: In
      values:
      - cert-manager
      - cainjector
      - webhook
    - key: app.kubernetes.io/component
      operator: In
      values:
      - controller
      - cainjector
      - webhook
  podMetricsEndpoints:
  - port: http-metrics
    interval: 60s
    path: /metrics
