apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: polaris
  namespace: flux-system
spec:
  interval: 30m0s
  releaseName: polaris
  targetNamespace: polaris
  install:
    createNamespace: false
  chart:
    spec:
      chart: polaris
      version: 5.19.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system
  values:
    config:
      checks:
        cpuRequestsMissing: warning
        memoryRequestsMissing: warning
        cpuLimitsMissing: warning
        memoryLimitsMissing: warning
        notReadOnlyRootFilesystem: warning
        privilegeEscalationAllowed: danger
        runAsRootAllowed: warning
        insecureCapabilities: danger
        hostNetworkSet: warning
        hostPIDSet: danger
        hostIPCSet: danger
        pullPolicyNotAlways: ignore
        tagNotSpecified: warning
        priorityClassNotSet: warning
        missingPodDisruptionBudget: warning
      exemptions:
        - namespace: kube-system
          controllerNames:
            - kube-flannel
          rules:
            - hostNetworkSet
            - runAsRootAllowed
            - privilegeEscalationAllowed
            - insecureCapabilities
        - namespace: kube-system
          controllerNames:
            - coredns
          rules:
            - priorityClassNotSet
        - namespace: longhorn-system
          controllerNames:
            - longhorn-manager
            - longhorn-csi-plugin
          rules:
            - hostNetworkSet
            - runAsRootAllowed
            - privilegeEscalationAllowed
            - insecureCapabilities
    dashboard:
      enable: true
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts: []
